config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  resources :places
  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  post'contact', to: 'pages#contact'
  get "infos", to: 'pages#infos', as: :infos

  # Generic syntax:
  # verb 'path', to: 'controller#action'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :first_name
  attribute :last_name, validate: true
  attribute :message
  attribute :email
  validates_format_of :email, with: /\A[^@\s]+@[^@\s]+\z/i

  def headers
    {
      #this is the subject for the email generated, it can be anything you want
      subject: "My Contact Form",
      to: 'chateaudelathibaudiere@gmail.com',
      from: %("#{name}" <#{email}>)
      #the from will display the name entered by the user followed by the email
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
before_action :contact_params, only: [:new, :create]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(:contact)
    @contact.request = request
      if @contact.deliver
        render json: {message: "Email sent successfully"}
      else
        render json: @contact.errors
      end
    end


  def contact_params
    params.require(:contact).permit(:first_name,:last_name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <viewport> -->
    <title>ChateauLaThibaudiere</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>

    <meta charset="utf-8" />
    <title>Add a default marker</title>
    <title>Display map navigation controls</title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.0.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.0.1/mapbox-gl.css' rel='stylesheet' />
    <style>
      body { margin: 0; padding: 0; }
      #map { position: absolute; top: 0; bottom: 0; width: 100%; }
    </style>
  </head>

  <body>
    <%= yield %>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoiY2hpYXJhbXRyIiwiYSI6ImNrZ3l6YzZlYTBxenYzMG9zcThtYTZ3amkifQ.7JNs5rpi6uCKbEmX40EqQg';
    var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/chiaramtr/ckjyi4u2i2qch17qzgl0529w3', // stylesheet location
    center: [-0.6373141584905248, 47.54282299664977], // starting position [lng, lat]
    zoom: 12 // starting zoom
    });

    // Add zoom and rotation controls to the map.
    map.addControl(new mapboxgl.NavigationControl());

    var marker = new mapboxgl.Marker()
    .setLngLat([-0.6373141584905248, 47.54282299664977])
    .addTo(map);
    </script>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container bg-contact">
    <div class="menu-container">
      <ul class="homepage-menu text--center">
        <li class="menu-item"><%= link_to "ACCUEIL", home_path %></li>
        <li class="menu-item"><%= link_to "LE DOMAINE", about_path %></li>
        <li class="menu-item"><%= link_to "CONTACT", contact_path %></li></li>
        <li class="menu-item"><%= link_to "INFORMATIONS PRATIQUES", infos_path %></li>
      </ul>
    </div>
    <div class="container-contact">
      <div class="wrap-contact text--center">
      <h1>NOUS CONTACTER</h1>
      <div class="contact-form text--center">
        <div class="input">
          <%= simple_form_for contact_path do |f| %>
            <%= f.input_field :first_name, placeholder: 'Prénom', :class => "input" %>
            <%= f.input_field :last_name, placeholder: 'Nom', :class => "input"%>
            <%= f.input_field :email, placeholder: 'Email', :class => "input"%>
            <%= f.input_field :message, as: :text, placeholder: 'Message', :input_html => {:rows => 20}, :class => "message_input"%>
            <%= f.button :submit, "Envoyer", class: "btn-radius btn-green btn-block" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container bg-homepage">
  <div class="row">
    <div class="col-12 text--center">
      <ul class="homepage-menu text--center">
        <li class="menu-item"><%= link_to "ACCUEIL", home_path %></li>
        <li class="menu-item"><%= link_to "LE DOMAINE", about_path %></li>
        <li class="menu-item"><%= link_to "CONTACT", contact_path %></li></li>
        <li class="menu-item"><%= link_to "INFORMATIONS PRATIQUES", infos_path %></li>
      </ul>
    </div>
    <div class="col-12">
      <div class="text--center">
        <h1>LA THIBAUDIERE</h1>
      </div>
    </div>
  </div>
</div>

app/views/pages/infos.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text--center">
      <ul class="homepage-menu text--center">
        <li class="menu-item"><%= link_to "ACCUEIL", home_path %></li>
        <li class="menu-item"><%= link_to "LE DOMAINE", about_path %></li>
        <li class="menu-item"><%= link_to "CONTACT", contact_path %></li></li>
        <li class="menu-item"><%= link_to "INFORMATIONS PRATIQUES", infos_path %></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-12 text--center map-info">
      <h4> Accès et périodes de visite</h4>
    </div>
  </div>
  <div class="row info-content">
    <div class="col-5">
      <div id='map' style='height: 400px;'></div>
    </div>
    <div class="col-2">

    </div>
    <div class="col-3">
      <div class="info-photo">
        <%= image_tag("la-thib-contact.jpg", height: 400, :style => 'border: 1px solid #000;')%>
      </div>
    </div>
  </div>
</div>